name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create model directory
        working-directory: ./app-tfjs/public
        run: mkdir -p model

      - name: Download models
        working-directory: ./app-tfjs/public/model
        run: curl --remote-name-all '${{ secrets.DOWNLOAD_ROOT }}{group1-shard1of3.bin,group1-shard2of3.bin,group1-shard3of3.bin,model.json}'
      
      - name: Install dependencies
        working-directory: ./app-tfjs
        run: npm ci

      - name: Build
        working-directory: ./app-tfjs
        run: npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_0B4414900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "app-tfjs/dist"
          skip_app_build: true
          skip_api_build: true
